SELECT a.ID as ID, b.FISH_NAME as FISH_NAME, a.LENGTH as LENGTH
FROM FISH_INFO a
JOIN FISH_NAME_INFO b ON a.FISH_TYPE = b.FISH_TYPE
WHERE (a.FISH_TYPE, a.LENGTH) in (
SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
FROM FISH_INFO
GROUP BY FISH_TYPE)
