name: Update Algorithm Stats

on:
    schedule:
        - cron: "0 0 * * *" # 매일 00시 실행
    workflow_dispatch:

permissions:
    contents: write # 레포에 commit/push 권한

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requests beautifulsoup4

            - name: Update stats
              run: python update_stats.py

            - name: Commit changes
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@github.com"
                  git add README.md
                  git commit -m "chore: update algorithm stats" || echo "No changes to commit"
                  git push
