name: Update Algorithm Stats

on:
    schedule:
        - cron: "0 0 * * *" # 매일 00시 실행
    workflow_dispatch:

permissions:
    contents: write # 레포에 commit/push 권한

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Update stats
              run: python update_stats.py

            - name: Commit & Push changes
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@users.noreply.github.com"
                  git add README.md
                  git commit -m "chore: auto update stats" || echo "No changes to commit"
                  git push
